import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 bg-[url('https://your-image-url.jpg')] bg-cover bg-center`}>
        
        {/* Full-width Navigation Bar */}
        <nav className="bg-gradient-to-b from-[#29C75E] to-[#666666] p-4 rounded-b-lg shadow-md w-full">
          <div className="max-w-7xl mx-auto flex items-center justify-between">
            <div className="text-white text-2xl font-semibold">
              {/* You can put your logo or title here */}
              Philippine Insider Intelligence Magazines
            </div>
            <div className="space-x-4">
              <a href="#" className="text-white hover:text-blue-200">About</a>
              <a href="#" className="text-white hover:text-blue-200">CEOs</a>
              <a href="#" className="text-white hover:text-blue-200">FAQ</a>
            </div>
          </div>
        </nav>  

        {/* Children Content */}
        <div className="container mx-auto px-4 py-6">
          {children}
        </div>
        
      </body>
    </html>
  );
}
